version: "3"

services:
  rss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - rss_network

  db:
    image: postgres:13
    volumes:
      - rss_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - rss_network

volumes:
  rss_postgres_data:

networks:
  rss_network: