version: "3"

services:

  rss_api:
    build:
      context: .
      dockerfile: server.dockerfile.test
    env_file:
      - .env.test
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - rss_network

  db:
    image: postgres:13
    env_file:
      - .env.test
    volumes:
      - rss_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - rss_network

volumes:
  rss_postgres_data:

networks:
  rss_network: