version: "3"

services:

  rss_api:
    build:
      context: .
      dockerfile: ./docker-images/rss-api.dockerfile.test
    env_file:
      - .env.test
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - rss_network

  db:
    image: postgres:13
    env_file:
      - .env.test
    ports:
      - "5432:5432"
    networks:
      - rss_network

networks:
  rss_network: