
name: Build and Deploy to GAE

on:
  push:
    branches:
      - gcp

  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Auth
      id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.4.0

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"